# Generated by Django 3.2 on 2022-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_delete_note_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
